-- -- Show diagnostic in floating window when over current underlined diagnostic
-- vim.api.nvim_create_autocmd("CursorHold", {
--   pattern = "*",
--   callback = function()
--     vim.diagnostic.open_float(nil, {
--       border = "rounded",
--       -- <C-l> to move into floating window
--       focusable = true,
--       source = "always",
--       prefix = " ",
--       scope = "cursor",
--       close_events = { "BufLeave", "CursorMoved", "InsertEnter", "FocusLost" },
--     })
--   end,
-- })
